//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_metar_display {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("csharp_metar_display.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automated observation.
        /// </summary>
        internal static string AutomatedObservation {
            get {
                return ResourceManager.GetString("AutomatedObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        internal static string CardinalEast {
            get {
                return ResourceManager.GetString("CardinalEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EastNorthEast.
        /// </summary>
        internal static string CardinalEastNorthEast {
            get {
                return ResourceManager.GetString("CardinalEastNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EastSouthEast.
        /// </summary>
        internal static string CardinalEastSouthEast {
            get {
                return ResourceManager.GetString("CardinalEastSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        internal static string CardinalNorth {
            get {
                return ResourceManager.GetString("CardinalNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NorthEast.
        /// </summary>
        internal static string CardinalNorthEast {
            get {
                return ResourceManager.GetString("CardinalNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NorthNorthEast.
        /// </summary>
        internal static string CardinalNorthNorthEast {
            get {
                return ResourceManager.GetString("CardinalNorthNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NorthNorthWest.
        /// </summary>
        internal static string CardinalNorthNorthWest {
            get {
                return ResourceManager.GetString("CardinalNorthNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NorthEast.
        /// </summary>
        internal static string CardinalNorthWest {
            get {
                return ResourceManager.GetString("CardinalNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        internal static string CardinalSouth {
            get {
                return ResourceManager.GetString("CardinalSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SouthEast.
        /// </summary>
        internal static string CardinalSouthEast {
            get {
                return ResourceManager.GetString("CardinalSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SouthSouthEast.
        /// </summary>
        internal static string CardinalSouthSouthEast {
            get {
                return ResourceManager.GetString("CardinalSouthSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SouthSouthWest.
        /// </summary>
        internal static string CardinalSouthSouthWest {
            get {
                return ResourceManager.GetString("CardinalSouthSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SouthWest.
        /// </summary>
        internal static string CardinalSouthWest {
            get {
                return ResourceManager.GetString("CardinalSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        internal static string CardinalWest {
            get {
                return ResourceManager.GetString("CardinalWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WestNorthWest.
        /// </summary>
        internal static string CardinalWestNorthWest {
            get {
                return ResourceManager.GetString("CardinalWestNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WestSouthWest.
        /// </summary>
        internal static string CardinalWestSouthWest {
            get {
                return ResourceManager.GetString("CardinalWestSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broken.
        /// </summary>
        internal static string CloudsAmountBKN {
            get {
                return ResourceManager.GetString("CloudsAmountBKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CloudsAmountCLR {
            get {
                return ResourceManager.GetString("CloudsAmountCLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to few.
        /// </summary>
        internal static string CloudsAmountFEW {
            get {
                return ResourceManager.GetString("CloudsAmountFEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no significant cloud.
        /// </summary>
        internal static string CloudsAmountNSC {
            get {
                return ResourceManager.GetString("CloudsAmountNSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CloudsAmountNULL {
            get {
                return ResourceManager.GetString("CloudsAmountNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overcast.
        /// </summary>
        internal static string CloudsAmountOVC {
            get {
                return ResourceManager.GetString("CloudsAmountOVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scattered.
        /// </summary>
        internal static string CloudsAmountSCT {
            get {
                return ResourceManager.GetString("CloudsAmountSCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical visibility.
        /// </summary>
        internal static string CloudsAmountVV {
            get {
                return ResourceManager.GetString("CloudsAmountVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {feet} feet ({meters} meters).
        /// </summary>
        internal static string CloudsDetails {
            get {
                return ResourceManager.GetString("CloudsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clouds.
        /// </summary>
        internal static string CloudsLabel {
            get {
                return ResourceManager.GetString("CloudsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot measure.
        /// </summary>
        internal static string CloudsTypeCannotMeasure {
            get {
                return ResourceManager.GetString("CloudsTypeCannotMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cumulonimbus.
        /// </summary>
        internal static string CloudsTypeCB {
            get {
                return ResourceManager.GetString("CloudsTypeCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CloudsTypeNULL {
            get {
                return ResourceManager.GetString("CloudsTypeNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to towering cumulus.
        /// </summary>
        internal static string CloudsTypeTCU {
            get {
                return ResourceManager.GetString("CloudsTypeTCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downward trend.
        /// </summary>
        internal static string DownwardTrend {
            get {
                return ResourceManager.GetString("DownwardTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METAR is not valid.
        /// </summary>
        internal static string MetarIsNotValid {
            get {
                return ResourceManager.GetString("MetarIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Date.
        /// </summary>
        internal static string ObservationDateLabel {
            get {
                return ResourceManager.GetString("ObservationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {metarDay} day of the month at {metarTime} UTC.
        /// </summary>
        internal static string ObservationDetails {
            get {
                return ResourceManager.GetString("ObservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {hectoPascal} hPa ({mercuryInch} inHg).
        /// </summary>
        internal static string PressureDetails {
            get {
                return ResourceManager.GetString("PressureDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string PressureLabel {
            get {
                return ResourceManager.GetString("PressureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prevailingVisibility} meters.
        /// </summary>
        internal static string PrevailingVisibility {
            get {
                return ResourceManager.GetString("PrevailingVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Metar.
        /// </summary>
        internal static string RawMetarLabel {
            get {
                return ResourceManager.GetString("RawMetarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperature {airTemperatureC}°C ({airTemperatureF}°F), dew point: {dewTemperatureC}°C ({dewTemperatureF}°F).
        /// </summary>
        internal static string TemperaturesDetails {
            get {
                return ResourceManager.GetString("TemperaturesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatures.
        /// </summary>
        internal static string TemperaturesLabel {
            get {
                return ResourceManager.GetString("TemperaturesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upward trend.
        /// </summary>
        internal static string UpwardTrend {
            get {
                return ResourceManager.GetString("UpwardTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 km or more (6 statute-miles).
        /// </summary>
        internal static string Visibility10KmOrMore {
            get {
                return ResourceManager.GetString("Visibility10KmOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling And Visibility OK.
        /// </summary>
        internal static string VisibilityCAVOK {
            get {
                return ResourceManager.GetString("VisibilityCAVOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string VisibilityLabel {
            get {
                return ResourceManager.GetString("VisibilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than {visualRangeMin} meters, more than {visualRangeMax} meters.
        /// </summary>
        internal static string VisualRangeBetween {
            get {
                return ResourceManager.GetString("VisualRangeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {visualRangeMin} meters.
        /// </summary>
        internal static string VisualRangeExact {
            get {
                return ResourceManager.GetString("VisualRangeExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for runway {runway}.
        /// </summary>
        internal static string VisualRangeForRunway {
            get {
                return ResourceManager.GetString("VisualRangeForRunway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Range.
        /// </summary>
        internal static string VisualRangeLabel {
            get {
                return ResourceManager.GetString("VisualRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {meanDirectionDegrees} degrees ({meanDirectionCardinal}) at {speedKnot} knots.
        /// </summary>
        internal static string WindDetails {
            get {
                return ResourceManager.GetString("WindDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (variable between {windDirectionVariationDegrees} degrees ({windDirectionVariationCardinal}) and {windDirectionVariationMaxDegrees} degrees ({windDirectionVariationMaxCardinal)})).
        /// </summary>
        internal static string WindDirectionVariations {
            get {
                return ResourceManager.GetString("WindDirectionVariations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gusts up to {windGustsKnot} knots.
        /// </summary>
        internal static string WindGusts {
            get {
                return ResourceManager.GetString("WindGusts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string WindLabel {
            get {
                return ResourceManager.GetString("WindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windshear all runways.
        /// </summary>
        internal static string WindshearAllRunways {
            get {
                return ResourceManager.GetString("WindshearAllRunways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windshear.
        /// </summary>
        internal static string WindshearLabel {
            get {
                return ResourceManager.GetString("WindshearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windshear on runway {wr}.
        /// </summary>
        internal static string WindshearOnRunway {
            get {
                return ResourceManager.GetString("WindshearOnRunway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        internal static string WindVariableDirection {
            get {
                return ResourceManager.GetString("WindVariableDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string WindWith {
            get {
                return ResourceManager.GetString("WindWith", resourceCulture);
            }
        }
    }
}
